import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { LocalService } from '../../services/local.service';
import { AppService } from '../../services/app.service';
import { FormArrayName } from '../../../node_modules/@angular/forms';
import { CrudService } from '../../services/crud.service';
/**
 * Generated class for the WelcomePage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-welcome',
  templateUrl: 'welcome.html',
})
export class WelcomePage {

  constructor(
    public navCtrl: NavController,
    public navParams: NavParams,
    private appService: AppService,
    private crudService: CrudService
  ) {
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad WelcomePage');
  }

  insertDB() {
    let ARRAY = [
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Phúc Xá', WCODE: '1' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Trúc Bạch', WCODE: '4' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Vĩnh Phúc', WCODE: '6' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Cống Vị', WCODE: '7' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Liễu Giai', WCODE: '8' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Nguyễn Trung Trực', WCODE: '10' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Quán Thánh', WCODE: '13' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Ngọc Hà', WCODE: '16' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Điện Biên', WCODE: '19' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Đội Cấn', WCODE: '22' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Ngọc Khánh', WCODE: '25' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Kim Mã', WCODE: '28' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Giảng Võ', WCODE: '31' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Đình', DCODE: '1', WARD: 'Phường Thành Công', WCODE: '34' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Phúc Tân', WCODE: '37' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Đồng Xuân', WCODE: '40' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Mã', WCODE: '43' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Buồm', WCODE: '46' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Đào', WCODE: '49' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Bồ', WCODE: '52' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Cửa Đông', WCODE: '55' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Lý Thái Tổ', WCODE: '58' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Bạc', WCODE: '61' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Gai', WCODE: '64' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Chương Dương', WCODE: '67' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Trống', WCODE: '70' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Cửa Nam', WCODE: '73' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Bông', WCODE: '76' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Tràng Tiền', WCODE: '79' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Trần Hưng Đạo', WCODE: '82' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Phan Chu Trinh', WCODE: '85' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàn Kiếm', DCODE: '2', WARD: 'Phường Hàng Bài', WCODE: '88' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Tây Hồ', DCODE: '3', WARD: 'Phường Phú Thượng', WCODE: '91' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Tây Hồ', DCODE: '3', WARD: 'Phường Nhật Tân', WCODE: '94' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Tây Hồ', DCODE: '3', WARD: 'Phường Tứ Liên', WCODE: '97' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Tây Hồ', DCODE: '3', WARD: 'Phường Quảng An', WCODE: '100' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Tây Hồ', DCODE: '3', WARD: 'Phường Xuân La', WCODE: '103' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Tây Hồ', DCODE: '3', WARD: 'Phường Yên Phụ', WCODE: '106' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Tây Hồ', DCODE: '3', WARD: 'Phường Bưởi', WCODE: '109' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Tây Hồ', DCODE: '3', WARD: 'Phường Thụy Khuê', WCODE: '112' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Thượng Thanh', WCODE: '115' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Ngọc Thụy', WCODE: '118' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Giang Biên', WCODE: '121' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Đức Giang', WCODE: '124' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Việt Hưng', WCODE: '127' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Gia Thụy', WCODE: '130' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Ngọc Lâm', WCODE: '133' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Phúc Lợi', WCODE: '136' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Bồ Đề', WCODE: '139' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Sài Đồng', WCODE: '142' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Long Biên', WCODE: '145' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Thạch Bàn', WCODE: '148' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Phúc Đồng', WCODE: '151' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Long Biên', DCODE: '4', WARD: 'Phường Cự Khối', WCODE: '154' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Cầu Giấy', DCODE: '5', WARD: 'Phường Nghĩa Đô', WCODE: '157' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Cầu Giấy', DCODE: '5', WARD: 'Phường Nghĩa Tân', WCODE: '160' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Cầu Giấy', DCODE: '5', WARD: 'Phường Mai Dịch', WCODE: '163' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Cầu Giấy', DCODE: '5', WARD: 'Phường Dịch Vọng', WCODE: '166' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Cầu Giấy', DCODE: '5', WARD: 'Phường Dịch Vọng Hậu', WCODE: '167' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Cầu Giấy', DCODE: '5', WARD: 'Phường Quan Hoa', WCODE: '169' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Cầu Giấy', DCODE: '5', WARD: 'Phường Yên Hoà', WCODE: '172' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Cầu Giấy', DCODE: '5', WARD: 'Phường Trung Hoà', WCODE: '175' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Cát Linh', WCODE: '178' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Văn Miếu', WCODE: '181' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Quốc Tử Giám', WCODE: '184' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Láng Thượng', WCODE: '187' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Ô Chợ Dừa', WCODE: '190' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Văn Chương', WCODE: '193' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Hàng Bột', WCODE: '196' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Láng Hạ', WCODE: '199' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Khâm Thiên', WCODE: '202' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Thổ Quan', WCODE: '205' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Nam Đồng', WCODE: '208' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Trung Phụng', WCODE: '211' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Quang Trung', WCODE: '214' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Trung Liệt', WCODE: '217' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Phương Liên', WCODE: '220' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Thịnh Quang', WCODE: '223' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Trung Tự', WCODE: '226' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Kim Liên', WCODE: '229' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Phương Mai', WCODE: '232' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Ngã Tư Sở', WCODE: '235' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đống Đa', DCODE: '6', WARD: 'Phường Khương Thượng', WCODE: '238' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quận Hai Bà Trưng', DCODE: '7', WARD: 'Phường Nguyễn Du', WCODE: '241' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Bạch Đằng', WCODE: '244' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Phạm Đình Hổ', WCODE: '247' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Bùi Thị Xuân', WCODE: '250' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Ngô Thì Nhậm', WCODE: '253' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Lê Đại Hành', WCODE: '256' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Đồng Nhân', WCODE: '259' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Phố Huế', WCODE: '262' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Đống Mác', WCODE: '265' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Thanh Lương', WCODE: '268' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Thanh Nhàn', WCODE: '271' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Cầu Dền', WCODE: '274' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Bách Khoa', WCODE: '277' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Đồng Tâm', WCODE: '280' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Vĩnh Tuy', WCODE: '283' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Bạch Mai', WCODE: '286' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Quỳnh Mai', WCODE: '289' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Quỳnh Lôi', WCODE: '292' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Minh Khai', WCODE: '295' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hai Bà Trưng', DCODE: '7', WARD: 'Phường Trương Định', WCODE: '298' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Thanh Trì', WCODE: '301' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Vĩnh Hưng', WCODE: '304' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Định Công', WCODE: '307' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Mai Động', WCODE: '310' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Tương Mai', WCODE: '313' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Đại Kim', WCODE: '316' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Tân Mai', WCODE: '319' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Hoàng Văn Thụ', WCODE: '322' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Giáp Bát', WCODE: '325' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Lĩnh Nam', WCODE: '328' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Thịnh Liệt', WCODE: '331' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Trần Phú', WCODE: '334' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Hoàng Liệt', WCODE: '337' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoàng Mai', DCODE: '8', WARD: 'Phường Yên Sở', WCODE: '340' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Nhân Chính', WCODE: '343' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Thượng Đình', WCODE: '346' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Khương Trung', WCODE: '349' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Khương Mai', WCODE: '352' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Thanh Xuân Trung', WCODE: '355' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Phương Liệt', WCODE: '358' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Hạ Đình', WCODE: '361' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Khương Đình', WCODE: '364' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Thanh Xuân Bắc', WCODE: '367' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Thanh Xuân Nam', WCODE: '370' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Xuân', DCODE: '9', WARD: 'Phường Kim Giang', WCODE: '373' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Thị trấn Sóc Sơn', WCODE: '376' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Bắc Sơn', WCODE: '379' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Minh Trí', WCODE: '382' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Hồng Kỳ', WCODE: '385' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Nam Sơn', WCODE: '388' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Trung Giã', WCODE: '391' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Tân Hưng', WCODE: '394' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Minh Phú', WCODE: '397' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Phù Linh', WCODE: '400' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Bắc Phú', WCODE: '403' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Tân Minh', WCODE: '406' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Quang Tiến', WCODE: '409' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Hiền Ninh', WCODE: '412' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Tân Dân', WCODE: '415' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Tiên Dược', WCODE: '418' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Việt Long', WCODE: '421' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Xuân Giang', WCODE: '424' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Mai Đình', WCODE: '427' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Đức Hoà', WCODE: '430' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Thanh Xuân', WCODE: '433' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Đông Xuân', WCODE: '436' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Kim Lũ', WCODE: '439' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Phú Cường', WCODE: '442' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Phú Minh', WCODE: '445' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Phù Lỗ', WCODE: '448' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Sóc Sơn', DCODE: '16', WARD: 'Xã Xuân Thu', WCODE: '451' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Thị trấn Đông Anh', WCODE: '454' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Xuân Nộn', WCODE: '457' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Thuỵ Lâm', WCODE: '460' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Bắc Hồng', WCODE: '463' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Nguyên Khê', WCODE: '466' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Nam Hồng', WCODE: '469' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Tiên Dương', WCODE: '472' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Vân Hà', WCODE: '475' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Uy Nỗ', WCODE: '478' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Vân Nội', WCODE: '481' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Liên Hà', WCODE: '484' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Việt Hùng', WCODE: '487' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Kim Nỗ', WCODE: '490' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Kim Chung', WCODE: '493' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Dục Tú', WCODE: '496' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Đại Mạch', WCODE: '499' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Vĩnh Ngọc', WCODE: '502' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Cổ Loa', WCODE: '505' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Hải Bối', WCODE: '508' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Xuân Canh', WCODE: '511' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Võng La', WCODE: '514' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Tầm Xá', WCODE: '517' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Mai Lâm', WCODE: '520' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đông Anh', DCODE: '17', WARD: 'Xã Đông Hội', WCODE: '523' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Thị trấn Yên Viên', WCODE: '526' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Yên Thường', WCODE: '529' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Yên Viên', WCODE: '532' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Ninh Hiệp', WCODE: '535' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Đình Xuyên', WCODE: '538' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Dương Hà', WCODE: '541' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Phù Đổng', WCODE: '544' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Trung Mầu', WCODE: '547' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Lệ Chi', WCODE: '550' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Cổ Bi', WCODE: '553' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Đặng Xá', WCODE: '556' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Phú Thị', WCODE: '559' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Kim Sơn', WCODE: '562' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Thị trấn Trâu Quỳ', WCODE: '565' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Dương Quang', WCODE: '568' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Dương Xá', WCODE: '571' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Đông Dư', WCODE: '574' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Đa Tốn', WCODE: '577' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Kiêu Kỵ', WCODE: '580' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Bát Tràng', WCODE: '583' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Kim Lan', WCODE: '586' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Gia Lâm', DCODE: '18', WARD: 'Xã Văn Đức', WCODE: '589' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Cầu Diễn', WCODE: '592' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Xuân Phương', WCODE: '622' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Phương Canh', WCODE: '623' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Mỹ Đình 1', WCODE: '625' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Mỹ Đình 2', WCODE: '626' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Tây Mỗ', WCODE: '628' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Mễ Trì', WCODE: '631' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Phú Đô', WCODE: '632' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Đại Mỗ', WCODE: '634' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Nam Từ Liêm', DCODE: '19', WARD: 'Phường Trung Văn', WCODE: '637' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Thị trấn Văn Điển', WCODE: '640' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Tân Triều', WCODE: '643' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Thanh Liệt', WCODE: '646' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Tả Thanh Oai', WCODE: '649' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Hữu Hoà', WCODE: '652' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Tam Hiệp', WCODE: '655' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Tứ Hiệp', WCODE: '658' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Yên Mỹ', WCODE: '661' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Vĩnh Quỳnh', WCODE: '664' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Ngũ Hiệp', WCODE: '667' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Duyên Hà', WCODE: '670' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Ngọc Hồi', WCODE: '673' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Vạn Phúc', WCODE: '676' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Đại áng', WCODE: '679' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Liên Ninh', WCODE: '682' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Trì', DCODE: '20', WARD: 'Xã Đông Mỹ', WCODE: '685' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Thượng Cát', WCODE: '595' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Liên Mạc', WCODE: '598' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Đông Ngạc', WCODE: '601' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Đức Thắng', WCODE: '602' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Thụy Phương', WCODE: '604' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Tây Tựu', WCODE: '607' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Xuân Đỉnh', WCODE: '610' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Xuân Tảo', WCODE: '611' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Minh Khai', WCODE: '613' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Cổ Nhuế 1', WCODE: '616' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Cổ Nhuế 2', WCODE: '617' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Phú Diễn', WCODE: '619' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Bắc Từ Liêm', DCODE: '21', WARD: 'Phường Phúc Diễn', WCODE: '620' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Thị trấn Chi Đông', WCODE: '8973' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Đại Thịnh', WCODE: '8974' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Kim Hoa', WCODE: '8977' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Thạch Đà', WCODE: '8980' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Tiến Thắng', WCODE: '8983' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Tự Lập', WCODE: '8986' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Thị trấn Quang Minh', WCODE: '8989' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Thanh Lâm', WCODE: '8992' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Tam Đồng', WCODE: '8995' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Liên Mạc', WCODE: '8998' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Vạn Yên', WCODE: '9001' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Chu Phan', WCODE: '9004' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Tiến Thịnh', WCODE: '9007' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Mê Linh', WCODE: '9010' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Văn Khê', WCODE: '9013' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Hoàng Kim', WCODE: '9016' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Tiền Phong', WCODE: '9019' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mê Linh', DCODE: '250', WARD: 'Xã Tráng Việt', WCODE: '9022' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Nguyễn Trãi', WCODE: '9538' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Mộ Lao', WCODE: '9541' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Văn Quán', WCODE: '9542' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Vạn Phúc', WCODE: '9544' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Yết Kiêu', WCODE: '9547' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Quang Trung', WCODE: '9550' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường La Khê', WCODE: '9551' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Phú La', WCODE: '9552' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Phúc La', WCODE: '9553' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Hà Cầu', WCODE: '9556' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Yên Nghĩa', WCODE: '9562' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Kiến Hưng', WCODE: '9565' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Phú Lãm', WCODE: '9568' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Phú Lương', WCODE: '9571' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Dương Nội', WCODE: '9886' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Đồng Mai', WCODE: '10117' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hà Đông', DCODE: '268', WARD: 'Phường Biên Giang', WCODE: '10123' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Lê Lợi', WCODE: '9574' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Phú Thịnh', WCODE: '9577' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Ngô Quyền', WCODE: '9580' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Quang Trung', WCODE: '9583' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Sơn Lộc', WCODE: '9586' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Xuân Khanh', WCODE: '9589' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Xã Đường Lâm', WCODE: '9592' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Viên Sơn', WCODE: '9595' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Xã Xuân Sơn', WCODE: '9598' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Trung Hưng', WCODE: '9601' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Xã Thanh Mỹ', WCODE: '9604' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Phường Trung Sơn Trầm', WCODE: '9607' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Xã Kim Sơn', WCODE: '9610' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Xã Sơn Đông', WCODE: '9613' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thị xã Sơn Tây', DCODE: '269', WARD: 'Xã Cổ Đông', WCODE: '9616' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Thị trấn Tây Đằng', WCODE: '9619' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Phú Cường', WCODE: '9625' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Cổ Đô', WCODE: '9628' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Tản Hồng', WCODE: '9631' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Vạn Thắng', WCODE: '9634' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Châu Sơn', WCODE: '9637' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Phong Vân', WCODE: '9640' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Phú Đông', WCODE: '9643' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Phú Phương', WCODE: '9646' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Phú Châu', WCODE: '9649' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Thái Hòa', WCODE: '9652' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Đồng Thái', WCODE: '9655' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Phú Sơn', WCODE: '9658' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Minh Châu', WCODE: '9661' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Vật Lại', WCODE: '9664' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Chu Minh', WCODE: '9667' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Tòng Bạt', WCODE: '9670' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Cẩm Lĩnh', WCODE: '9673' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Sơn Đà', WCODE: '9676' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Đông Quang', WCODE: '9679' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Tiên Phong', WCODE: '9682' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Thụy An', WCODE: '9685' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Cam Thượng', WCODE: '9688' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Thuần Mỹ', WCODE: '9691' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Tản Lĩnh', WCODE: '9694' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Ba Trại', WCODE: '9697' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Minh Quang', WCODE: '9700' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Ba Vì', WCODE: '9703' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Vân Hòa', WCODE: '9706' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Yên Bài', WCODE: '9709' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ba Vì', DCODE: '271', WARD: 'Xã Khánh Thượng', WCODE: '9712' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Thị trấn Phúc Thọ', WCODE: '9715' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Vân Hà', WCODE: '9718' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Vân Phúc', WCODE: '9721' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Vân Nam', WCODE: '9724' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Xuân Phú', WCODE: '9727' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Phương Độ', WCODE: '9730' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Sen Chiểu', WCODE: '9733' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Cẩm Đình', WCODE: '9736' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Võng Xuyên', WCODE: '9739' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Thọ Lộc', WCODE: '9742' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Long Xuyên', WCODE: '9745' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Thượng Cốc', WCODE: '9748' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Hát Môn', WCODE: '9751' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Tích Giang', WCODE: '9754' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Thanh Đa', WCODE: '9757' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Trạch Mỹ Lộc', WCODE: '9760' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Phúc Hòa', WCODE: '9763' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Ngọc Tảo', WCODE: '9766' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Phụng Thượng', WCODE: '9769' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Tam Thuấn', WCODE: '9772' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Tam Hiệp', WCODE: '9775' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Hiệp Thuận', WCODE: '9778' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phúc Thọ', DCODE: '272', WARD: 'Xã Liên Hiệp', WCODE: '9781' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Thị trấn Phùng', WCODE: '9784' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Trung Châu', WCODE: '9787' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Thọ An', WCODE: '9790' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Thọ Xuân', WCODE: '9793' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Hồng Hà', WCODE: '9796' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Liên Hồng', WCODE: '9799' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Liên Hà', WCODE: '9802' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Hạ Mỗ', WCODE: '9805' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Liên Trung', WCODE: '9808' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Phương Đình', WCODE: '9811' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Thượng Mỗ', WCODE: '9814' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Tân Hội', WCODE: '9817' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Tân Lập', WCODE: '9820' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Đan Phượng', WCODE: '9823' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Đồng Tháp', WCODE: '9826' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Đan Phượng', DCODE: '273', WARD: 'Xã Song Phượng', WCODE: '9829' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Thị trấn Trạm Trôi', WCODE: '9832' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Đức Thượng', WCODE: '9835' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Minh Khai', WCODE: '9838' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Dương Liễu', WCODE: '9841' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Di Trạch', WCODE: '9844' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Đức Giang', WCODE: '9847' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Cát Quế', WCODE: '9850' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Kim Chung', WCODE: '9853' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Yên Sở', WCODE: '9856' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Sơn Đồng', WCODE: '9859' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Vân Canh', WCODE: '9862' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Đắc Sở', WCODE: '9865' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Lại Yên', WCODE: '9868' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Tiền Yên', WCODE: '9871' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Song Phương', WCODE: '9874' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã An Khánh', WCODE: '9877' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã An Thượng', WCODE: '9880' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Vân Côn', WCODE: '9883' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã La Phù', WCODE: '9889' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Hoài Đức', DCODE: '274', WARD: 'Xã Đông La', WCODE: '9892' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Đông Xuân', WCODE: '4939' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Thị trấn Quốc Oai', WCODE: '9895' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Sài Sơn', WCODE: '9898' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Phượng Cách', WCODE: '9901' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Yên Sơn', WCODE: '9904' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Ngọc Liệp', WCODE: '9907' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Ngọc Mỹ', WCODE: '9910' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Liệp Tuyết', WCODE: '9913' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Thạch Thán', WCODE: '9916' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Đồng Quang', WCODE: '9919' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Phú Cát', WCODE: '9922' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Tuyết Nghĩa', WCODE: '9925' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Nghĩa Hương', WCODE: '9928' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Cộng Hòa', WCODE: '9931' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Tân Phú', WCODE: '9934' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Đại Thành', WCODE: '9937' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Phú Mãn', WCODE: '9940' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Cấn Hữu', WCODE: '9943' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Tân Hòa', WCODE: '9946' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Hòa Thạch', WCODE: '9949' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Quốc Oai', DCODE: '275', WARD: 'Xã Đông Yên', WCODE: '9952' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Yên Trung', WCODE: '4927' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Yên Bình', WCODE: '4930' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Tiến Xuân', WCODE: '4936' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Thị trấn Liên Quan', WCODE: '9955' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Đại Đồng', WCODE: '9958' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Cẩm Yên', WCODE: '9961' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Lại Thượng', WCODE: '9964' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Phú Kim', WCODE: '9967' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Hương Ngải', WCODE: '9970' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Canh Nậu', WCODE: '9973' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Kim Quan', WCODE: '9976' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Dị Nậu', WCODE: '9979' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Bình Yên', WCODE: '9982' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Chàng Sơn', WCODE: '9985' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Thạch Hoà', WCODE: '9988' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Cần Kiệm', WCODE: '9991' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Hữu Bằng', WCODE: '9994' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Phùng Xá', WCODE: '9997' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Tân Xã', WCODE: '10000' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Thạch Xá', WCODE: '10003' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Bình Phú', WCODE: '10006' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Hạ Bằng', WCODE: '10009' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thạch Thất', DCODE: '276', WARD: 'Xã Đồng Trúc', WCODE: '10012' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Thị trấn Chúc Sơn', WCODE: '10015' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Thị trấn Xuân Mai', WCODE: '10018' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Phụng Châu', WCODE: '10021' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Tiên Phương', WCODE: '10024' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Đông Sơn', WCODE: '10027' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Đông Phương Yên', WCODE: '10030' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Phú Nghĩa', WCODE: '10033' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Trường Yên', WCODE: '10039' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Ngọc Hòa', WCODE: '10042' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Thủy Xuân Tiên', WCODE: '10045' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Thanh Bình', WCODE: '10048' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Trung Hòa', WCODE: '10051' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Đại Yên', WCODE: '10054' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Thụy Hương', WCODE: '10057' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Tốt Động', WCODE: '10060' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Lam Điền', WCODE: '10063' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Tân Tiến', WCODE: '10066' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Nam Phương Tiến', WCODE: '10069' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Hợp Đồng', WCODE: '10072' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Hoàng Văn Thụ', WCODE: '10075' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Hoàng Diệu', WCODE: '10078' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Hữu Văn', WCODE: '10081' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Quảng Bị', WCODE: '10084' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Mỹ Lương', WCODE: '10087' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Thượng Vực', WCODE: '10090' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Hồng Phong', WCODE: '10093' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Đồng Phú', WCODE: '10096' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Trần Phú', WCODE: '10099' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Văn Võ', WCODE: '10102' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Đồng Lạc', WCODE: '10105' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Hòa Chính', WCODE: '10108' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Chương Mỹ', DCODE: '277', WARD: 'Xã Phú Nam An', WCODE: '10111' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Thị trấn Kim Bài', WCODE: '10114' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Cự Khê', WCODE: '10120' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Bích Hòa', WCODE: '10126' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Mỹ Hưng', WCODE: '10129' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Cao Viên', WCODE: '10132' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Bình Minh', WCODE: '10135' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Tam Hưng', WCODE: '10138' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Thanh Cao', WCODE: '10141' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Thanh Thùy', WCODE: '10144' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Thanh Mai', WCODE: '10147' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Thanh Văn', WCODE: '10150' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Đỗ Động', WCODE: '10153' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Kim An', WCODE: '10156' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Kim Thư', WCODE: '10159' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Phương Trung', WCODE: '10162' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Tân Ước', WCODE: '10165' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Dân Hòa', WCODE: '10168' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Liên Châu', WCODE: '10171' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Cao Dương', WCODE: '10174' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Xuân Dương', WCODE: '10177' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thanh Oai', DCODE: '278', WARD: 'Xã Hồng Dương', WCODE: '10180' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Thị trấn Thường Tín', WCODE: '10183' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Ninh Sở', WCODE: '10186' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Nhị Khê', WCODE: '10189' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Duyên Thái', WCODE: '10192' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Khánh Hà', WCODE: '10195' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Hòa Bình', WCODE: '10198' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Văn Bình', WCODE: '10201' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Hiền Giang', WCODE: '10204' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Hồng Vân', WCODE: '10207' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Vân Tảo', WCODE: '10210' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Liên Phương', WCODE: '10213' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Văn Phú', WCODE: '10216' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Tự Nhiên', WCODE: '10219' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Tiền Phong', WCODE: '10222' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Hà Hồi', WCODE: '10225' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Thư Phú', WCODE: '10228' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Nguyễn Trãi', WCODE: '10231' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Quất Động', WCODE: '10234' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Chương Dương', WCODE: '10237' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Tân Minh', WCODE: '10240' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Lê Lợi', WCODE: '10243' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Thắng Lợi', WCODE: '10246' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Dũng Tiến', WCODE: '10249' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Thống Nhất', WCODE: '10252' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Nghiêm Xuyên', WCODE: '10255' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Tô Hiệu', WCODE: '10258' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Văn Tự', WCODE: '10261' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Vạn Điểm', WCODE: '10264' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Thường Tín', DCODE: '279', WARD: 'Xã Minh Cường', WCODE: '10267' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Thị trấn Phú Minh', WCODE: '10270' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Thị trấn Phú Xuyên', WCODE: '10273' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Hồng Minh', WCODE: '10276' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Phượng Dực', WCODE: '10279' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Văn Nhân', WCODE: '10282' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Thụy Phú', WCODE: '10285' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Tri Trung', WCODE: '10288' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Đại Thắng', WCODE: '10291' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Phú Túc', WCODE: '10294' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Văn Hoàng', WCODE: '10297' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Hồng Thái', WCODE: '10300' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Hoàng Long', WCODE: '10303' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Quang Trung', WCODE: '10306' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Nam Phong', WCODE: '10309' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Nam Triều', WCODE: '10312' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Tân Dân', WCODE: '10315' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Sơn Hà', WCODE: '10318' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Chuyên Mỹ', WCODE: '10321' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Khai Thái', WCODE: '10324' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Phúc Tiến', WCODE: '10327' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Vân Từ', WCODE: '10330' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Tri Thủy', WCODE: '10333' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Đại Xuyên', WCODE: '10336' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Phú Yên', WCODE: '10339' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Bạch Hạ', WCODE: '10342' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Quang Lãng', WCODE: '10345' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Châu Can', WCODE: '10348' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Phú Xuyên', DCODE: '280', WARD: 'Xã Minh Tân', WCODE: '10351' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Thị trấn Vân Đình', WCODE: '10354' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Viên An', WCODE: '10357' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Viên Nội', WCODE: '10360' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Hoa Sơn', WCODE: '10363' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Quảng Phú Cầu', WCODE: '10366' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Trường Thịnh', WCODE: '10369' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Cao Thành', WCODE: '10372' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Liên Bạt', WCODE: '10375' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Sơn Công', WCODE: '10378' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Đồng Tiến', WCODE: '10381' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Phương Tú', WCODE: '10384' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Trung Tú', WCODE: '10387' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Đồng Tân', WCODE: '10390' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Tảo Dương Văn', WCODE: '10393' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Vạn Thái', WCODE: '10396' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Minh Đức', WCODE: '10399' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Hòa Lâm', WCODE: '10402' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Hòa Xá', WCODE: '10405' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Trầm Lộng', WCODE: '10408' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Kim Đường', WCODE: '10411' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Hòa Nam', WCODE: '10414' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Hòa Phú', WCODE: '10417' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Đội Bình', WCODE: '10420' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Đại Hùng', WCODE: '10423' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Đông Lỗ', WCODE: '10426' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Phù Lưu', WCODE: '10429' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Đại Cường', WCODE: '10432' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Lưu Hoàng', WCODE: '10435' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Ứng Hòa', DCODE: '281', WARD: 'Xã Hồng Quang', WCODE: '10438' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Thị trấn Đại Nghĩa', WCODE: '10441' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Đồng Tâm', WCODE: '10444' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Thượng Lâm', WCODE: '10447' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Tuy Lai', WCODE: '10450' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Phúc Lâm', WCODE: '10453' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Mỹ Thành', WCODE: '10456' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Bột Xuyên', WCODE: '10459' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã An Mỹ', WCODE: '10462' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Hồng Sơn', WCODE: '10465' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Lê Thanh', WCODE: '10468' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Xuy Xá', WCODE: '10471' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Phùng Xá', WCODE: '10474' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Phù Lưu Tế', WCODE: '10477' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Đại Hưng', WCODE: '10480' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Vạn Kim', WCODE: '10483' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Đốc Tín', WCODE: '10486' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Hương Sơn', WCODE: '10489' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Hùng Tiến', WCODE: '10492' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã An Tiến', WCODE: '10495' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Hợp Tiến', WCODE: '10498' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã Hợp Thanh', WCODE: '10501' },
      { CITY: 'Hà Nội', CCODE: '1', DIST: 'Mỹ Đức', DCODE: '282', WARD: 'Xã An Phú', WCODE: '10504' },
    ]
    console.log(ARRAY);
    let data = {
      HANOI: ARRAY
    }
    this.crudService.basicInfoCreate('DVHC/1', data)
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
      })
  }

  removeDuplicate() {
    let array = [
    
    ];
    console.log(array);
    let uniqArray = this.appService.removeDuplicateObjectFromArray(array, 'CCODE');
    console.log(uniqArray);
    let BasicInfo = {
      CITIES: uniqArray
    }
    this.crudService.basicInfoCreate('INFOS/BASIC', BasicInfo)
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
      })

  }

}
