import { iLoc } from "./loc.interface";
import { iPart } from "../pages/case-information-fill/case-information-fill";

export interface iPatient {
    PAT_FNAME: string,
    PAT_LNAME: string,
    PAT_YoB: string,
    PAT_SEX: string,
    PAT_RES_ID: string,
    PAT_CONTACT_ADDRESS: string,
    PAT_CONTACT_WARD: string,
    PAT_CONTACT_DIST: string,
    PAT_CONTACT_CITY: string,
    PAT_CONTACT_LOC: iLoc,
    PAT_HOME_ADDRESS: string,
    PAT_HOME_WARD: string,
    PAT_HOME_DIST: string,
    PAT_HOME_CITY: string,
    PAT_HOME_LOC: iLoc,
    PAT_TEL: string,
    PAT_DISABLED_YEAR: string,
    PAT_DISABLED_TYPE: string,
    PAT_DISABLED_PARTS: iPart[],
    PAT_DISABLED_REASONS: iPart[],
    PAT_DISABLED_SUPPORT_RECEIVED: boolean,
    PAT_DISABLED_SUPPORT_TYPE: string,
    PAT_DISABLED_SUPPORT_RECEIVED_YEAR: string,
    PAT_DISABLED_LAST_SUPPORT_YEAR: string,
    PAT_DISABLED_LAST_SUPPORT_SPONSORS: iPart[],
    PAT_AMPUTATION_YEAR: string,
    PAT_AMPUTATION_PARTS: iPart[],
    PAT_AMPUTATION_REASONS: iPart[],
    PAT_AMPUTATION_LEGS: string,
    PAT_AMPUTATION_LAST_LEG_YEAR: string,
    PAT_AMPUTATION_LAST_SPONSORS: iPart[],
    PAT_JOB: iPart,
    PAT_DATE_CREATE: string,
    PAT_ID: string,
    PAT_MAIL: string,
    // PAT_NAME: string,
    PAT_AMP: string,
    PAT_CONVOQ: string,
    PAT_CONVOQ_DATE: string,
    PAT_REMARK: string,
    PAT_KIND: string,
    PAT_REFERRAL_ID: string,
    PAT_REFLEAD_ID: string,
    PAT_REFORG: string,
    PAT_MOVEABILITY: string,
    PAT_MVA_ID: string,
    PAT_SVP: string,
    PAT_SVCPRO_ID: string,
    PAT_STATE: string,
    PAT_isSELECTED: boolean,
    PAT_INV_FROM: string,
    PAT_INV_TO: string,
    PAT_MILESTONE: string[],
    PAT_OTHER: any,
    PAT_IMAGES: iIMG[],
    PAT_DOCS: iIMG[],
    PAT_COST: any,
    PAT_COST_LIST: any,
    PAT_NOTES: iNote[],
    PAT_QUESTIONS: iQuestion[],
    PAT_CASENUMBER: string
}

export interface iIMG {
    DES: string,
    URL: string,
    TIME: string,
    BY: string,
    BY_UID: string,
}

export interface iNote {
    NOTE: string,
    TIME: string,
    BY: string,
    ROLE: string,
    BY_UID: string
}

export interface iQuestion {
    QUEST: string,
    TIME: string,
    BY: string,
    BY_UID: string,
    ROLE: string,
    isAQuestion: boolean
}