import { iLoc } from "./loc.interface";
export interface iPrivacy{
    PRI_FNAME: boolean,
    PRI_LNAME: boolean,
    PRI_YoB: boolean,
    PRI_SEX: boolean,
    PRI_RES_ID: boolean,
    PRI_CONTACT_ADDRESS: boolean,
    PRI_CONTACT_WARD: boolean,
    PRI_CONTACT_DIST: boolean,
    PRI_CONTACT_CITY: boolean,
    PRI_HOME_ADDRESS: boolean,
    PRI_HOME_WARD: boolean,
    PRI_HOME_DIST: boolean,
    PRI_HOME_CITY: boolean,
    PRI_TEL: boolean,
    PRI_DISABLED_YEAR: boolean,
    PRI_DISABLED_TYPE: boolean,
    PRI_DISABLED_PARTS: boolean,
    PRI_DISABLED_REASONS: boolean,
    PRI_DISABLED_SUPPORT_RECEIVED: boolean,
    PRI_DISABLED_SUPPORT_TYPE: boolean,
    PRI_DISABLED_SUPPORT_RECEIVED_YEAR: boolean,
    PRI_DISABLED_LAST_SUPPORT_YEAR: boolean,
    PRI_DISABLED_LAST_SUPPORT_SPONSORS: boolean,
    PRI_AMPUTATION_YEAR: boolean,
    PRI_AMPUTATION_PARTS: boolean,
    PRI_AMPUTATION_REASONS: boolean,
    PRI_AMPUTATION_LEGS: boolean,
    PRI_AMPUTATION_LAST_LEG_YEAR: boolean,
    PRI_AMPUTATION_LAST_SPONSORS: boolean,
    PRI_JOB: boolean,
    PRI_DATE_CREATE: boolean,
}
