export interface iQuestForm {
    ID: string,
    DATE: string,
    INFO: {
        COUNTRY: string,
        CENTERNAME: string, 
        FILENUMBER: string, 
        GENDER: string, 
        EVAL_PLACE: string, 
        NAME_BENEFICIARY: string,
        OCCUPATION: string,
        LIVING_ENV: string,
        EVAL_DATE: string,
        YoB: string,
        YoAmDis: string,
        CauseOfAmDis: string
    },
    DEVICE:{
        Q1: string[],
        Q2: string[],
        Q2A: string,
        Q2B: string,
        Q2C: string,
        Q3: string[],
        Q3A: string,
        Q3B: string,
        Q3C: string,
        Q4: boolean,
    },
    ACCESSSABILITY:{
        Q5: string[],
        Q6: boolean,
        Q6A: string,
        Q7: string,
        Q8: string,
        Q9: string,
        Q10: string,
        Q11: string,
        Q12: string[]
    }, 
    QUALITY: {
        Q13: string,
        Q14: string,
        Q15: string,
        Q16: string,
        Q17: string,
        Q18: string,
        Q19: string,
        Q20: string,
        Q20A: string, 
    },
    IMPACT: {
        Q21: string[],
        Q22: string,
        Q23: string,
        Q23A: string,
        Q24: string,
        Q25: string,
        Q26: string,
        Q27: string,
        Q28: string,
        Q29: string,

    },
    ENDING: {
        COMMENT: string,
        INTERPRETER_NAME: string,
        INTERPRETER_W4C: boolean,
        EVALUATOR_NAME: string,
        EVALUATOR_W4C: boolean,
    }
}